services:
  bot:
    build: .
    container_name: mishgan-twitch-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./storage:/app/storage
    command: ["python", "bot.py"]
