"""
Orchestrates the enrichment of games with short, Russian descriptions
generated by GPT based on the English summary from IGDB.
"""

import asyncio
import json

from sqlalchemy.ext.asyncio import AsyncSession

from database.db import AsyncSessionLocal
from database.models import Game, GameMetadataIGDB
from pipeline.load.load_recommendations import (
    iter_games_missing_short_description,
    set_game_short_description,
)
from services.gpt_service import generate_short_description
from utils.logger import get_logger

CONCURRENT_GPT_REQUESTS = 1
GAME_DELAY = 15


async def _process_game(session: AsyncSession, game: Game, semaphore: asyncio.Semaphore) -> bool:
    logger = get_logger("orchestrator.enrich_descriptions")

    async with semaphore:
        from sqlalchemy import select
        result = await session.execute(select(GameMetadataIGDB).where(GameMetadataIGDB.game_id == game.id))
        meta = result.scalar_one_or_none()

        if not meta or not meta.raw_payload:
            logger.warning(f"Game '{game.name}' is missing IGDB metadata or raw_payload.")
            await asyncio.sleep(GAME_DELAY)
            return False

        try:
            payload = meta.raw_payload if isinstance(meta.raw_payload, dict) else json.loads(meta.raw_payload)
            summary = payload.get("summary")
        except (json.JSONDecodeError, AttributeError):
            logger.warning(f"Could not parse raw_payload for game: {game.name}")
            await asyncio.sleep(GAME_DELAY)
            return False

        if not summary or not isinstance(summary, str) or len(summary.strip()) < 10:
            logger.warning(
                "Summary too short (%d chars) for: %s",
                len(summary.strip()) if isinstance(summary, str) else 0,
                game.name,
            )
            await asyncio.sleep(GAME_DELAY)
            return False

        logger.info(f"Generating description for: {game.name}")
        try:
            short_description = await generate_short_description(summary)
        except Exception as e:
            logger.error(f"GPT request failed for '{game.name}': {e}")
            await asyncio.sleep(GAME_DELAY)
            return False

        if not short_description:
            logger.warning("GPT returned no description for: %s", game.name)
            await asyncio.sleep(GAME_DELAY)
            return False

        if await set_game_short_description(session, game, short_description):
            logger.info(f"Successfully generated and set description for: {game.name}")
            await asyncio.sleep(GAME_DELAY)
            return True

        logger.warning("set_game_short_description returned False for: %s", game.name)

    await asyncio.sleep(GAME_DELAY)
    return False


async def _run(process_limit: int = 10):
    logger = get_logger("orchestrator.enrich_descriptions")

    async with AsyncSessionLocal() as session:
        games_to_process = list(await iter_games_missing_short_description(session, limit=process_limit))
        if not games_to_process:
            logger.info("No games found missing a short description.")
            return

        logger.info(f"Found {len(games_to_process)} games to process.")

        semaphore = asyncio.Semaphore(CONCURRENT_GPT_REQUESTS)
        tasks = [_process_game(session, game, semaphore) for game in games_to_process]
        results = await asyncio.gather(*tasks)
        updated_count = sum(1 for r in results if r is True)

        if updated_count > 0:
            await session.commit()
            logger.info(f"Committed {updated_count} new short descriptions to the database.")
        else:
            logger.info("No descriptions were updated in this run.")
            await session.rollback()


def enrich_descriptions_with_gpt(process_limit: int = 10):
    asyncio.run(_run(process_limit))


if __name__ == "__main__":
    enrich_descriptions_with_gpt()
